from __future__ import annotations

import argparse
import hashlib
import json
import re
import zipfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATE_PATH = ROOT / "art-production-spec" / "ART_PRODUCTION_STATE.json"
MANIFEST_PATH = ROOT / "art-production-spec" / "ART_ASSET_MANIFEST.json"
ASSET_ROOT = ROOT / "art-assets"
REQUIRED = [
    "ART_HANDOFF.md",
    "ART_OFFLINE_HANDOFF_GUIDE.md",
    "ART_SYNC_GUIDE.md",
    "HUMAN_REVIEW_GUIDE.md",
    "REFERENCE_ASSET_MAP.json",
    "art-production-spec/ART_PRODUCTION_STATE.json",
    "art-production-spec/ART_ASSET_MANIFEST.json",
    "art-production-spec/CHARACTER_BIBLE.md",
    "art-production-spec/ART_DIRECTION.md",
    "art-production-spec/PRODUCTION_RULES.md",
    "art-pipeline/asset_intake.py",
    "art-pipeline/handoff_check.py",
]

def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))

def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()

def safe_rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()

def collect_asset_files(asset_id: str) -> list[Path]:
    base = ASSET_ROOT / asset_id
    if not base.exists():
        return []
    return sorted(p for p in base.rglob("*") if p.is_file() and p.name != ".gitkeep")

def build(output: Path) -> Path:
    state = load_json(STATE_PATH)
    manifest = load_json(MANIFEST_PATH)
    asset_id = str(state.get("current_asset", "")).upper()
    if not re.fullmatch(r"[A-Z]\d{2}", asset_id):
        raise ValueError(f"Invalid STATE.current_asset: {asset_id!r}")

    missing = [p for p in REQUIRED if not (ROOT / p).is_file()]
    if missing:
        raise FileNotFoundError("Missing required files: " + ", ".join(missing))

    output = output.expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    package_name = f"PelicanWorkBench_Art_Handoff_{datetime.now(timezone.utc):%Y%m%d}_{asset_id}"
    included: list[Path] = []

    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as z:
        for rel in REQUIRED:
            p = ROOT / rel
            z.write(p, rel)
            included.append(p)

        # Package the current asset and the B01 style-anchor master/reference files
        for aid in {asset_id, "B01"}:
            for p in collect_asset_files(aid):
                z.write(p, safe_rel(p))
                included.append(p)

        metadata = {
            "schema_version": "1.0",
            "package_type": "HANDOFF",
            "project": state.get("project", "Pelican Workbench"),
            "repository": state.get("repository"),
            "branch": "main",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "current_asset": asset_id,
            "current_key": state.get("current_key"),
            "current_status": state.get("current_status"),
            "next_action": state.get("next_action"),
            "style_anchor": state.get("style_anchor", "B01"),
            "human_review_required": True,
            "approval_is_not_automatic": True,
            "source_commit": "generated by GitHub Actions from the pushed main revision",
            "notes": [
                "This package is a transport snapshot, not the project source of truth.",
                "GitHub main remains the canonical source of truth.",
                "B01 reference files are included when they exist in art-assets/B01/master or candidates.",
            ],
        }
        z.writestr("HANDOFF_PACKAGE.json", json.dumps(metadata, ensure_ascii=False, indent=2) + "\n")

        checks = {
            "schema_version": "1.0",
            "package_type": "HANDOFF",
            "files": [
                {"path": safe_rel(p), "sha256": sha256(p)}
                for p in sorted(set(included), key=lambda x: safe_rel(x))
            ],
        }
        z.writestr("checksums.json", json.dumps(checks, ensure_ascii=False, indent=2) + "\n")
        z.writestr(
            "PACKAGE_README.txt",
            "Pelican Workbench Art Handoff Package\n"
            "Generated automatically from GitHub main after a relevant push.\n"
            "Read ART_HANDOFF.md first. GitHub main is the source of truth.\n"
            f"Current asset: {asset_id} / {state.get('current_key')} / {state.get('current_status')} / {state.get('next_action')}\n",
        )
    return output

def validate(package: Path) -> tuple[bool, list[str]]:
    errors: list[str] = []
    try:
        z = zipfile.ZipFile(package, "r")
    except Exception as e:
        return False, [f"Invalid ZIP: {e}"]
    with z:
        names = set(z.namelist())
        for req in ["HANDOFF_PACKAGE.json", "checksums.json", "ART_HANDOFF.md", "art-production-spec/ART_PRODUCTION_STATE.json"]:
            if req not in names:
                errors.append(f"Missing: {req}")
        try:
            meta = json.loads(z.read("HANDOFF_PACKAGE.json").decode("utf-8"))
            if meta.get("package_type") != "HANDOFF":
                errors.append("package_type must be HANDOFF")
            if meta.get("human_review_required") is not True:
                errors.append("human_review_required must be true")
            if meta.get("approval_is_not_automatic") is not True:
                errors.append("approval_is_not_automatic must be true")
        except Exception as e:
            errors.append(f"Invalid HANDOFF_PACKAGE.json: {e}")
        try:
            checks = json.loads(z.read("checksums.json").decode("utf-8"))
            for item in checks.get("files", []):
                path, expected = item["path"], item["sha256"]
                if path not in names:
                    errors.append(f"Checksum file missing from ZIP: {path}")
                    continue
                actual = hashlib.sha256(z.read(path)).hexdigest()
                if actual != expected:
                    errors.append(f"SHA-256 mismatch: {path}")
        except Exception as e:
            errors.append(f"Invalid checksums.json: {e}")
    return not errors, errors

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", help="ZIP output path")
    ap.add_argument("--validate", help="Validate an existing ZIP")
    args = ap.parse_args()
    if args.output:
        out = build(Path(args.output))
        print(f"HANDOFF PACKAGE: EXPORTED {out}")
        return 0
    if args.validate:
        ok, errors = validate(Path(args.validate))
        if ok:
            print("HANDOFF PACKAGE: PASS")
            return 0
        print("HANDOFF PACKAGE: FAIL")
        for e in errors:
            print("ERROR:", e)
        return 2
    ap.error("use --output ZIP or --validate ZIP")

if __name__ == "__main__":
    raise SystemExit(main())
